---
- name: Copy file with owner and permissions
  copy:
    src: "{{ workdir }}/src/"
    dest: /etc/demo-ops/
    owner: demo
    mode: '0644'

- name: run demo-app
  command:
    chdir: /etc/demo-ops/
    cmd: docker-compose up -d