---
    apiVersion: apps/v1
    kind: Deployment                 
    metadata:
      name: ops-demo-app 
      namespace: demo-ops           
    spec:
      replicas: 2                  
      selector:
        matchLabels:
          app: ops-demo-app       
      template:                  
        metadata:
          labels:               
            app: ops-demo-app 
        spec:
          containers:
          - name: ops-demo-app
            image: omisha/zerodha-app
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080 
            livenessProbe:         
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 15
              timeoutSeconds: 5
            readinessProbe:       
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 10
              timeoutSeconds: 5                
            env:                   
              - name: DEMO_APP_ADDR
                value: 0.0.0.0:8080
              - name: DEMO_REDIS_ADDR
                value: redis:6379   
                
            
---

    apiVersion: v1
    kind: Service          
    metadata:
      name: ops-demo-app-service 
      namespace: demo-ops
    spec:
      type: NodePort            
      ports:                   
      - name: http
        port: 1234
        targetPort: 8080
      selector:
        app: ops-demo-app     